In [7]:
import pandas as pd

df = pd.read_csv("survey_results_public.csv", low_memory=False)
schema = pd.read_csv("survey_results_schema.csv")

df.head(15)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
6,7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
9,10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;W...,NaN,5400.0,4.0
10,11,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,Spring AI,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I don’t trust AI’s answers;When I have et...,Code writing. I know this sounds weird but you...,65691.0,10.0
11,12,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,3.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I need qu...,NaN,14400.0,8.0
12,13,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",10.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,1099.0,7.0
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
14,15,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Attending school (full-time);Attending school ...,15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,I don’t think I’ll need help from people anymore,senior development,NaN,9.0

In [8]:
schema.head(15)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0

In [15]:
#Task_1
total_responds = df.shape[0]
total_responds

49191

In [25]:
#Task_2
questions = set(schema["qname"])

columns = set(df.columns)

valid_columns = list(questions.intersection(columns))

complete_responses = df[valid_columns].dropna().shape[0]
print(complete_responses)

0

In [29]:
#Task_3
workexp = df["WorkExp"]

mean_val = workexp.mean()
median_val = workexp.median()
mode_val = workexp.mode()

print("Mean:", mean_val)
print("Median:", median_val)
print("Mode:", mode_val[0])

Mean: 13.367402606485907
Median: 10.0
Mode: 10.0

In [39]:
#Task_4
remote_count = df[df["RemoteWork"] == "Remote"].shape[0]
print(remote_count)

10931

In [46]:
#Task_5
python_users = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

percentage = python_users.mean() * 100
print(f"Відсоток респондентів, які програмують на Python: {percentage:.2f}%")

Відсоток респондентів, які програмують на Python:37.54%

In [52]:
#Task_6
online_learners = df["LearnCode"].str.contains("Online Courses", case=False, na=False)

count_online = online_learners.sum()
print(count_online)

10973

In [69]:
#Task_7
python_df = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]

salary_stats = python_df.groupby("Country")["ConvertedCompYearly"].agg(Average_Compensation="mean", Median_Compensation="median").reset_index()
salary_stats

,Country,Average_Compensation,Median_Compensation
0,Afghanistan,22328.666667,1000.0
1,Albania,47217.600000,50000.0
2,Algeria,20187.285714,7088.0
3,Andorra,226103.500000,226103.5
4,Angola,NaN,NaN
...,...,...,...
162,"Venezuela, Bolivarian Republic of...",9908.647059,3000.0
163,Viet Nam,218837.166667,8254.0
164,Yemen,32929.500000,23672.0
165,Zambia,5424.250000,3206.0
166,Zimbabwe,34000.000000,25500.0

In [74]:
#Task_8
top5 = df.sort_values(by="ConvertedCompYearly", ascending=False).head(5)

top5_education = top5[["ConvertedCompYearly", "EdLevel"]]
top5_education

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

In [78]:
#Task_9
df["Python"] = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

age_python = df.groupby("Age")["Python"].mean().reset_index()
age_python["Python"] = age_python["Python"] * 100

age_python.columns = ["Age_category", "Python_percentage"]
age_python

        Age_category  Python_percentage
0    18-24 years old          40.000000
1    25-34 years old          36.939282
2    35-44 years old          36.719281
3    45-54 years old          38.629482
4    55-64 years old          37.242955
5  65 years or older          31.634820
6  Prefer not to say          31.216931

In [82]:
#Task_10
rich_percentile = df["ConvertedCompYearly"].quantile(0.75)

filtered = df[
    (df["ConvertedCompYearly"] >= rich_percentile) &
    (df["RemoteWork"] == "Remote")]

top_industries = filtered["Industry"].value_counts()
print(top_industries)

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64